export const mockBoards = [
  {
    id: "demo-1",
    name: "科技新闻",
    icon: "💻",
    description: "国内外科技媒体头条",
    updated_at: new Date().toISOString(),
    articles: [{ count: 12 }],
    sources: [{ count: 3 }],
  },
  {
    id: "demo-2",
    name: "AI 动态",
    icon: "🤖",
    description: "人工智能行业最新进展",
    updated_at: new Date().toISOString(),
    articles: [{ count: 8 }],
    sources: [{ count: 2 }],
  },
  {
    id: "demo-3",
    name: "投资财经",
    icon: "📈",
    description: "股市、基金、宏观经济",
    updated_at: new Date().toISOString(),
    articles: [{ count: 15 }],
    sources: [{ count: 4 }],
  },
];

export const mockArticles = [
  {
    id: "a1",
    user_id: "demo",
    board_id: "demo-1",
    source_id: "s1",
    title: "OpenAI 发布 GPT-5 预览版，多模态能力大幅提升",
    summary:
      "OpenAI 今日凌晨发布了 GPT-5 的开发者预览版，新版本在图像理解、代码生成和推理能力上均有显著提升，开发者可以通过 API 抢先体验。",
    url: "https://example.com/1",
    image_url: null,
    author: "36氪",
    published_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    fetched_at: new Date().toISOString(),
    importance_score: 95,
    sentiment: "positive" as "positive" | "neutral" | "negative",
    tags: ["AI", "OpenAI"],
    is_read: false,
    is_favorite: false,
    hash: "hash1",
    created_at: new Date().toISOString(),
  },
  {
    id: "a2",
    user_id: "demo",
    board_id: "demo-1",
    source_id: "s2",
    title: "苹果 WWDC 2025 定档 6 月 9 日，AI 功能成焦点",
    summary:
      "苹果公司今日宣布 WWDC 2025 将于 6 月 9 日至 13 日举行，本次大会将重点关注 Apple Intelligence 的新进展，预计发布 iOS 19 和 macOS 16。",
    url: "https://example.com/2",
    image_url: null,
    author: "TechCrunch",
    published_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    fetched_at: new Date().toISOString(),
    importance_score: 88,
    sentiment: "neutral" as "positive" | "neutral" | "negative",
    tags: ["苹果", "WWDC"],
    is_read: false,
    is_favorite: false,
    hash: "hash2",
    created_at: new Date().toISOString(),
  },
  {
    id: "a3",
    user_id: "demo",
    board_id: "demo-1",
    source_id: "s3",
    title: "SpaceX 星舰第七次试飞取得部分成功",
    summary:
      "SpaceX 今日在德州博卡奇卡进行了星舰第七次轨道试飞，一级助推器成功回收，但二级飞船在再入大气层时失联，马斯克表示将分析数据后再次尝试。",
    url: "https://example.com/3",
    image_url: null,
    author: "BBC 中文",
    published_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    fetched_at: new Date().toISOString(),
    importance_score: 82,
    sentiment: "neutral" as "positive" | "neutral" | "negative",
    tags: ["SpaceX", "航天"],
    is_read: true,
    is_favorite: false,
    hash: "hash3",
    created_at: new Date().toISOString(),
  },
  {
    id: "a4",
    user_id: "demo",
    board_id: "demo-2",
    source_id: "s4",
    title: "Claude 4 正式版发布，编程能力超越 GPT-4",
    summary:
      "Anthropic 今日正式发布 Claude 4，在 SWE-bench 编程 benchmark 上得分达到 72.5%，超越了 GPT-4 的 67.3%，成为当前最强编程助手。",
    url: "https://example.com/4",
    image_url: null,
    author: "机器之心",
    published_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    fetched_at: new Date().toISOString(),
    importance_score: 92,
    sentiment: "positive" as "positive" | "neutral" | "negative",
    tags: ["AI", "Claude", "编程"],
    is_read: false,
    is_favorite: false,
    hash: "hash4",
    created_at: new Date().toISOString(),
  },
  {
    id: "a5",
    user_id: "demo",
    board_id: "demo-3",
    source_id: "s5",
    title: "央行宣布降准 0.5 个百分点，释放流动性约 1 万亿元",
    summary:
      "中国人民银行今日宣布下调金融机构存款准备金率 0.5 个百分点，预计释放长期资金约 1 万亿元，以支持实体经济发展。",
    url: "https://example.com/5",
    image_url: null,
    author: "财新网",
    published_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    fetched_at: new Date().toISOString(),
    importance_score: 90,
    sentiment: "positive" as "positive" | "neutral" | "negative",
    tags: ["央行", "降准", "宏观"],
    is_read: false,
    is_favorite: false,
    hash: "hash5",
    created_at: new Date().toISOString(),
  },
];

export const mockDailyReport = {
  id: "dr1",
  user_id: "demo",
  date: new Date().toISOString().split("T")[0],
  title: "今日日报",
  summary:
    "今日共收录 35 条资讯。AI 行业迎来 OpenAI GPT-5 预览版发布，引发广泛关注；科技领域苹果 WWDC 2025 定档；航天方面 SpaceX 星舰第七次试飞取得部分成功。整体市场情绪偏积极，正面资讯占比 60%。",
  article_count: 35,
  top_articles: {
    overallTitle: "今日日报",
    overallSummary:
      "今日共收录 35 条资讯。AI 行业迎来 OpenAI GPT-5 预览版发布，引发广泛关注；科技领域苹果 WWDC 2025 定档；航天方面 SpaceX 星舰第七次试飞取得部分成功。整体市场情绪偏积极。",
    boardSections: [
      {
        boardId: "demo-board-1",
        boardName: "AIHOT",
        boardIcon: "📁",
        summary: "AI 板块今日重点关注 OpenAI GPT-5 预览版发布及 Claude 4 正式版上线。",
        articleCount: 3,
        articles: mockArticles.slice(0, 3).map((a) => ({
          id: a.id,
          title: a.title,
          url: a.url,
          summary: a.summary,
          sourceName: a.author || "未知来源",
          publishedAt: a.published_at,
          importanceScore: a.importance_score,
          sentiment: a.sentiment,
          tags: a.tags,
        })),
      },
      {
        boardId: "demo-board-2",
        boardName: "价值投资大师语录",
        boardIcon: "📁",
        summary: "价值投资板块今日关注市场估值变化与投资者情绪。",
        articleCount: 0,
        articles: [],
      },
    ],
  },
  is_sent: true,
  sent_at: new Date().toISOString(),
  created_at: new Date().toISOString(),
};
